In [ ]:
!pip install spacy
!pip install spacy_langdetect

In [45]:
language_detect_dict = {'aa':'Afar','ab':'Abkhazian','af':'Afrikaans','ak':'Akan','sq':'Albanian','am':'Amharic','ar':'Arabic',
'an':'Aragonese','hy':'Armenian','as':'Assamese','av':'Avaric','ae':'Avestan','ay':'Aymara','az':'Azerbaijani','ba':'Bashkir',
'bm':'Bambara','eu':'Basque','be':'Belarusian','bn':'Bengali','bh':'Bihari','bi':'Bislama','bo':'Tibetan','bs':'Bosnian',
'br':'Breton','bg':'Bulgarian','my':'Burmese','ca':'Catalan','cs':'Czech','ch':'Chamorro','ce':'Chechen','zh':'Chinese',
'cu':'Church Slavic','cv':'Chuvash','kw':'Cornish','co':'Corsican',
'cr':'Cree','cy':'Welsh','cs':'Czech','da':'Danish','de':'German','dv':'Divehi','nl':'Dutch','dz':'Dzongkha',
'el':'Greek-Modern (1453-)','en':'English','eo':'Esperanto','et':'Estonian','eu':'Basque','ee':'Ewe','fo':'Faroese','fa':'Persian',
'fj':'Fijian','fi':'Finnish','fr':'French','fy':'Western Frisian','ff':'Fulah','Ga':'Georgian','gd':'Gaelic','ga':'Irish',
'gl':'Galician','gv':'Manx','el':'Greek-Modern (1453-)','gn':'Guarani','gu':'Gujarati','ht':'Haitian','ha':'Hausa',
'he':'Hebrew','hz':'Herero','hi':'Hindi','ho':'Hiri Motu','hr':'Croatian','hu':'Hungarian','hy':'Armenian','ig':'Igbo','is':'Icelandic',
'io':'Ido','ii':'Sichuan Yi; Nuosu','iu':'Inuktitut','ie':'Interlingue',
'ia':'Interlingua (International Auxiliary Language Association)','id':'Indonesian','ik':'Inupiaq','is':'Icelandic','it':'Italian',
'jv':'Javanese','ja':'Japanese','kl':'Kalaallisut','kn':'Kannada','ks':'Kashmiri','ka':'Georgian','kr':'Kanuri','kk':'Kazakh',
'km':'Central Khmer','ki':'Kikuyu; Gikuyu','rw':'Kinyarwanda','ky':'Kirghiz','kv':'Komi','kg':'Kongo','ko':'Korean',
'kj':'Kuanyama','ku':'Kurdish','lo':'Lao','la':'Latin','lv':'Latvian','li':'Limburgan','ln':'Lingala',
'lt':'Lithuanian','lb':'Luxembourgish; Letzeburgesch','lu':'Luba-Katanga','lg':'Ganda','mk':'Macedonian','mh':'Marshallese',
'ml':'Malayalam','mi':'Maori','mr':'Marathi','ms':'Malay','Mi':'Micmac','mk':'Macedonian','mg':'Malagasy','mt':'Maltese',
'mn':'Mongolian','mi':'Maori','ms':'Malay','my':'Burmese','na':'Nauru','nv':'Navajo; Navaho','nr':'Ndebele-South; South Ndebele',
'nd':'Ndebele-North; North Ndebele','ng':'Ndonga','ne':'Nepali','nl':'Dutch','nn':'Norwegian Nynorsk; Nynorsk:Norwegian',
'nb':'Bokmål-Norwegian; Norwegian Bokmål','no':'Norwegian','oc':'Occitan (post 1500)','oj':'Ojibwa','or':'Oriya','om':'Oromo',
'os':'Ossetian; Ossetic','pa':'Panjabi; Punjabi','fa':'Persian','pi':'Pali','pl':'Polish','pt':'Portugeese','ps':'Pushto; Pashto',
'qu':'Quechua','rm':'Romansh','ro':'Romanian','rn':'Rundi','ru':'Russian','sg':'Sango','sa':'Sanskrit',
'si':'Sinhalese','sk':'Slovak','sk':'Slovak','sl':'Slovenian','se':'Northern Sami','sm':'Samoan','sn':'Shona','sd':'Sindhi',
'so':'Somali','st':'Sotho-Southern','es':'Spanish','sq':'Albanian','sc':'Sardinian','sr':'Serbian','ss':'Swati',
'su':'Sundanese','sw':'Swahili','sv':'Sweedish','ty':'Tahitian','ta':'Tamil','tt':'Tatar','te':'Telugu','tg':'Tajik','tl':'Tagalog',
'th':'Thai','bo':'Tibetan','ti':'Tigrinya','to':'Tonga (Tonga Islands)','tn':'Tswana','ts':'Tsonga','tk':'Turkmen','tr':'Turkish',
'tw':'Twi','ug':'Uighur; Uyghur','uk':'Ukrainian','ur':'Urdu','uz':'Uzbek','ve':'Venda','vi':'Vietnamese','vo':'Volapük','cy':'Welsh',
'wa':'Walloon','wo':'Wolof','xh':'Xhosa','yi':'Yiddish','yo':'Yoruba','za':'Zhuang; Chuang','zh':'Chinese','zu':'Zulu'}

In [46]:
import spacy
from spacy.language import Language
from spacy_langdetect import LanguageDetector


class language_detector:
    def __init__(self):  
        self.nlp = spacy.load('en')
        self.nlp.max_length = 2000000
        self.nlp.add_pipe(LanguageDetector(), name='language_detector', last=True)

    def detect_lang(self,text):
        doc = self.nlp(text)
        detect_language = doc._.language
        return detect_language


    def map_lang_name(self,language):
        try:
            language_map = language_detect_dict
            lang_full_form = language_map[language['language']]
            lang_details = {'language_code': language['language'],
                    'language': lang_full_form,
                    'score': round(language['score'], 3)}
            return lang_details
        except:
            return {'language_code': 'uknown',
                    'language': 'not_known',
                    'score': 0}


if __name__ == "__main__":
    text_content = "Er lebt mit seinen Eltern und seiner Schwester in Berlin."
    model = language_detector()
    language = model.detect_lang(text_content)
    print("Score from spacy:", language)
    lang_details = model.map_lang_name(language)
    print("Language detected:", lang_details)

Score from spacy: {'language': 'de', 'score': 0.9999962224008985}
Language detected: {'language_code': 'de', 'language': 'German', 'score': 1.0}


In [47]:
class GetLanguage():
    def __init__(self):
        self.model = language_detector()

    def language_detection(self, text):
        # Store language detection results
        lang_results = []
        language = self.model.detect_lang(text)
        lang_results.append(self.model.map_lang_name(language))

        # Flatten list of multiple lists into one
        lang_results = [i for n, i in enumerate(lang_results) if i not in lang_results[n + 1:]]
        if len(lang_results) > 0:
            return {'lang_detected': lang_results}
        else:
            return {'lang_detected': None}

In [48]:
Model = GetLanguage()

In [49]:
Model.language_detection("This is a gun.")['lang_detected'][0]['language']

'English'

In [16]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('/content/drive/MyDrive/dataset/Language Detection.csv')

In [33]:
df['Language'] = df['Language'].map(lambda x : x.strip().lower())

In [34]:
df['Language'].unique()

array(['english', 'malayalam', 'hindi', 'tamil', 'portugeese', 'french',
       'dutch', 'spanish', 'greek', 'russian', 'danish', 'italian',
       'turkish', 'sweedish', 'arabic', 'german', 'kannada'], dtype=object)

In [50]:
pred = []
for text in df['Text'].values:
    pred.append(Model.language_detection(text)['lang_detected'][0]['language'].strip().lower())

In [41]:
from sklearn.metrics import classification_report,confusion_matrix

In [51]:
np.unique(pred)

array(['afrikaans', 'albanian', 'arabic', 'bulgarian', 'catalan',
       'croatian', 'czech', 'danish', 'dutch', 'english', 'estonian',
       'finnish', 'french', 'german', 'greek-modern (1453-)', 'hindi',
       'hungarian', 'indonesian', 'italian', 'kannada', 'latvian',
       'lithuanian', 'macedonian', 'malayalam', 'marathi', 'norwegian',
       'not_known', 'persian', 'polish', 'portugeese', 'romanian',
       'russian', 'slovak', 'slovenian', 'somali', 'spanish', 'sweedish',
       'tagalog', 'tamil', 'turkish', 'ukrainian', 'vietnamese', 'welsh'],
      dtype='<U20')

In [52]:
print(classification_report(df['Language'].values,pred))

                      precision    recall  f1-score   support

           afrikaans       0.00      0.00      0.00         0
            albanian       0.00      0.00      0.00         0
              arabic       1.00      0.99      1.00       536
           bulgarian       0.00      0.00      0.00         0
             catalan       0.00      0.00      0.00         0
            croatian       0.00      0.00      0.00         0
               czech       0.00      0.00      0.00         0
              danish       0.94      0.84      0.89       428
               dutch       0.97      0.86      0.92       546
             english       0.99      0.96      0.97      1385
            estonian       0.00      0.00      0.00         0
             finnish       0.00      0.00      0.00         0
              french       0.98      0.97      0.98      1014
              german       0.98      0.95      0.97       470
               greek       0.00      0.00      0.00       365
greek-m

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [54]:
print(confusion_matrix(df['Language'].values,pred))

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 533 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
